"""add extracted_values

Revision ID: 2cd8794ab54a
Revises: 3fc6c5a3c89e
Create Date: 2026-06-05 20:25:21.711386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd8794ab54a'
down_revision: Union[str, Sequence[str], None] = '3fc6c5a3c89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value_json', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='proposed', nullable=False),
    sa.Column('target_row_table', sa.String(), nullable=True),
    sa.Column('target_row_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('extracted_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_values_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_values_document_id'))

    op.drop_table('extracted_values')
    # ### end Alembic commands ###
