"""add profile

Revision ID: 80894c48dffc
Revises: 5d9e09f14d06
Create Date: 2026-06-05 11:03:09.297100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80894c48dffc'
down_revision: Union[str, Sequence[str], None] = '5d9e09f14d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('lmp_date', sa.String(), nullable=True),
    sa.Column('edd_source', sa.String(), nullable=True),
    sa.Column('prepreg_weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('units_weight', sa.String(), server_default='kg', nullable=False),
    sa.Column('units_length', sa.String(), server_default='cm', nullable=False),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('postpartum', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
