"""add bp_readings

Revision ID: f9112e3654b8
Revises: 594c4ca2398a
Create Date: 2026-06-05 19:20:53.801302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9112e3654b8'
down_revision: Union[str, Sequence[str], None] = '594c4ca2398a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bp_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('arm', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('source', sa.String(), server_default='self', nullable=False),
    sa.Column('source_report_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('bp_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bp_readings_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bp_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bp_readings_recorded_at'))

    op.drop_table('bp_readings')
    # ### end Alembic commands ###
