"""add symptom_logs

Revision ID: 3fc6c5a3c89e
Revises: c11f737124be
Create Date: 2026-06-05 20:05:50.859284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc6c5a3c89e'
down_revision: Union[str, Sequence[str], None] = 'c11f737124be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('symptom', sa.String(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('source', sa.String(), server_default='self', nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('symptom_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_logs_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_logs_symptom'), ['symptom'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_logs_symptom'))
        batch_op.drop_index(batch_op.f('ix_symptom_logs_recorded_at'))

    op.drop_table('symptom_logs')
    # ### end Alembic commands ###
