"""add appointment_checklists

Revision ID: f67c39b327d1
Revises: 26559cebf01c
Create Date: 2026-06-05 21:49:13.353759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67c39b327d1'
down_revision: Union[str, Sequence[str], None] = '26559cebf01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_checklists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('finalized', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('checklist_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('why_it_matters', sa.String(), nullable=True),
    sa.Column('answer_text', sa.String(), nullable=True),
    sa.Column('sort_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('checklist_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_questions_appointment_id'), ['appointment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_questions_appointment_id'))

    op.drop_table('checklist_questions')
    op.drop_table('appointment_checklists')
    # ### end Alembic commands ###
