"""add weight provenance

Revision ID: 594c4ca2398a
Revises: ad9709f89001
Create Date: 2026-06-05 18:46:20.429239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594c4ca2398a'
down_revision: Union[str, Sequence[str], None] = 'ad9709f89001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), server_default='self', nullable=False))
        batch_op.add_column(sa.Column('source_report_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_logs', schema=None) as batch_op:
        batch_op.drop_column('source_report_id')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
