"""add glucose_readings

Revision ID: c11f737124be
Revises: f9112e3654b8
Create Date: 2026-06-05 19:37:25.272411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11f737124be'
down_revision: Union[str, Sequence[str], None] = 'f9112e3654b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glucose_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('reading_type', sa.String(), nullable=False),
    sa.Column('meal', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('source', sa.String(), server_default='self', nullable=False),
    sa.Column('source_report_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('glucose_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glucose_readings_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glucose_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glucose_readings_recorded_at'))

    op.drop_table('glucose_readings')
    # ### end Alembic commands ###
